@startuml
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml
title __WWW's Class Diagram__\n

  namespace edu.mah.www {
    class edu.mah.www.DIWire {
        ~ CALIB_DIR_CCW : int
        ~ CALIB_DIR_CW : int
        ~ CALIB_DIR_NONE : int
        ~ CALIB_EDIT : int
        ~ CALIB_NEW : int

    }
  }
  

  namespace edu.mah.www {
    class edu.mah.www.DIWire.BezSpec {
        ~ x1 : float
        ~ x2 : float
        ~ x3 : float
        ~ x4 : float
        ~ y1 : float
        ~ y2 : float
        ~ y3 : float
        ~ y4 : float
    }
  }
  

  namespace edu.mah.www {
    class edu.mah.www.DIWire.DIWDropListener {
        ~ bgColor : int
        ~ hover : boolean
        ~ img : PImage
        + checkDropHover()
        + draw()
        + dropEnter()
        + dropEvent()
        + dropLeave()
        + setTarget()
        ~ DIWDropListener()
    }
  }
  

  namespace edu.mah.www {
    class edu.mah.www.DIWire.JSONFilter {
        + accept()
    }
  }
  

  namespace edu.mah.www {
    class edu.mah.www.DIWire.MainMenuActionListener {
        + actionPerformed()
    }
  }
  

  namespace edu.mah.www {
    class edu.mah.www.DIWire.Segment {
        ~ ents : ArrayList<StringDict>
        ~ ex : float
        ~ ey : float
        ~ sx : float
        ~ sy : float
        + reverse()
        + toString()
        ~ Segment()
    }
  }
  

  namespace edu.mah.www {
    class edu.mah.www.DIWire.WirePoint {
        ~ pointPause : boolean
        ~ pt : RPoint
        ~ stat : int
        + toString()
        ~ WirePoint()
        ~ WirePoint()
        ~ WirePoint()
    }
  }
  

  namespace edu.mah.www {
    class edu.mah.www.DIWire.WirePoints {
        ~ angles : FloatList
        ~ bendDir : boolean
        ~ continuousBendDist : float
        ~ curveIsClosed : boolean
        ~ diameters : FloatList
        ~ feeds : FloatList
        ~ modified : boolean
        ~ nAngleWarnings : int
        ~ nFeedWarnings : int
        ~ pts : ArrayList<WirePoint>
        ~ startPoint : int
        ~ WirePoints()
    }
  }
  

  edu.mah.www.DIWire -up-|> processing.core.PApplet
  edu.mah.www.DIWire o-- edu.mah.www.DIWire.DIWDropListener : dropListener
  edu.mah.www.DIWire +-down- edu.mah.www.DIWire.BezSpec
  edu.mah.www.DIWire +-down- edu.mah.www.DIWire.DIWDropListener
  edu.mah.www.DIWire +-down- edu.mah.www.DIWire.JSONFilter
  edu.mah.www.DIWire +-down- edu.mah.www.DIWire.MainMenuActionListener
  edu.mah.www.DIWire +-down- edu.mah.www.DIWire.Segment
  edu.mah.www.DIWire +-down- edu.mah.www.DIWire.WirePoint
  edu.mah.www.DIWire +-down- edu.mah.www.DIWire.WirePoints
  edu.mah.www.DIWire.DIWDropListener -up-|> sojamo.drop.DropListener
  edu.mah.www.DIWire.JSONFilter .up.|> java.io.FilenameFilter
  edu.mah.www.DIWire.MainMenuActionListener .up.|> java.awt.event.ActionListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
